CREATE TABLE IF NOT EXISTS `User` (
   id  INT AUTO_INCREMENT PRIMARY KEY,
   email VARCHAR(30) NOT NULL UNIQUE,
   userId VARCHAR(20) NOT NULL UNIQUE,
   password VARCHAR(20) NOT NULL,
   createdAt DATETIME DEFAULT CURRENT_TIMESTAMP,
   updatedAt DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
)